---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-v1
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
      version: v1
  template:
    metadata:
      labels:
        app: first-app
        version: v1
        istio: monitor
    spec:
      containers:
        - image: docker/example-voting-app-vote
          imagePullPolicy: Always
          name: first-app
          env:
            - name: SERVICE
              value: first-app
            - name: VERSION
              value: v1
          ports:
            - name: http
              containerPort: 8080
